### ISSUE TITLE
Enhancement Request: More ``Random'' Control

### ISSUE THREAD

**Issue by rickhg12hs** [feliixx/mongoplayground#107]
Awesome tool!  Thanks!

It would be useful if there was some control over randomness.  For example, when specifying `fromArray` with `"randomOrder": true`, the array elements are selected randomly, I suppose, but each press of the <kbd>run</kbd> button generates the exact same array.  This is useful for many testing scenarios, but more control would also be nice.

Perhaps adding an option to specify a `"randomSeed"` would be useful.  By specifying a `"randomSeed"`, each run *would* generate the same `"content"`.  Without specifying `"randomSeed"`, each run would generate *new* random `"content"`.

It would definitely be useful to have just one overall `"randomSeed"`, and perhaps useful to some to have a separate `"randomSeed"` for each instance of a `"type"` that uses randomness.

**Comment by feliixx** [comment]
Hi @rickhg12hs, 

yes, each run of the same config will always return the same results. This is intended for the playground because if a playground is shared, everybody should see the same result when running it 

To get different results for each run, you can use the command line version directly ( -> [mgodatagen](https://github.com/feliixx/mgodatagen) ) as it always use a random seed. 

hope this helps !

**Comment by rickhg12hs** [comment]
How about keeping the default behavior and having an optional `"randomSeed": 0, or False, or ...` that would randomize the `"content"`?  :-)

**Comment by feliixx** [comment]
Yes it would work, but I don't want to add this possibility in the playground 

Using mgodatagen directly doesn't work for you ?

**Comment by rickhg12hs** [comment]
Yes, `mgodatagen` works great, although I wish I didn't need access to a running MongoDB to prototype collections. feliixx/mgodatagen#77

**Comment by rickhg12hs** [comment]
Thanks for enhancing `mgodatagen`!
