### ISSUE TITLE
`mgodatagen`: offset trouble for `double` generator?

### ISSUE THREAD

**Issue by rickhg12hs** [feliixx/mongoplayground#152]
Using a `mgodatagen` configuration of:
```json
[
  {
    "collection": "collection",
    "count": 10,
    "content": {
      "array": {
        "type": "array",
        "minLength": 10,
        "maxLength": 10,
        "arrayContent": {
          "type": "double",
          "min": -1.0,
          "max": 1.0
        }
      }
    }
  }
]
```
... all the `"array"` values are negative.

I haven't tested the standalone `mgodatagen` to see if the behavior is the same.

**Comment by feliixx** [comment]
Interresting. I've investigated the code in `mgodatagen`, and indeed all values are negative. 

However, note that all values are in the [-1, 1] interval, so the output is correct, it's just not uniformly distributed. 

I'm planning to do a refactoring in `mgodatagen` to update the source of randomness in order to fix issue like this, maybe next month if I can find some time. 
As this issue is not directly related to `mongoplayground`, I'm closing it for now, but thanks for reporting this !
