### ISSUE TITLE
Error using $dateToString

### ISSUE THREAD

**Issue by mahiworkpro** [feliixx/mongoplayground#19]
Hi, I tried to use mongoplayground.net. I faced the issue **error in query: fail to parse content of query: json: cannot unmarshal array into Go value of type primitive.M** Can you please help. I'm trying to convert an ISO DateTime to EST Date (yyyy-mm-dd) format.

Input Document:
```
[
  {
    "item": "abc",
    "price": 10,
    "quantity": 2,
    "date": "2014-01-01T08:15:39.736Z"
  }
```
Query Used:
```db.collection.aggregate([{
    $project: {
        "yearMonthDayUTC": {
            "$dateToString": {
                format: "%Y-%m-%d",
                date: "$date"
            }
        }
    }
  }
])```

**Comment by feliixx** [comment]
Hi @mahiworkpro, 

this is because the `date` field in your input document is a `string`, and not an `ISODate`. Try to define it like this: 

`"date": ISODate("2014-01-01T08:15:39.736Z")`

or 

```
"date": {
    "$date": "2014-01-01T08:15:39.736Z"
}
```

see for example: 
- https://mongoplayground.net/p/mh2a3M3tW01
- https://mongoplayground.net/p/TsG18vrIKJd
